.TH lis_array_matmat 3 "3 Dec 2014" "Man Page" "Lis Library Functions"

.SH NAME

lis_array_matmat \- calculate the matrix-matrix product

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_array_matmat\fR(\fBLIS_INT n\fR, \fBLIS_SCALAR a[]\fR, \fBLIS_SCALAR b[]\fR, \fBLIS_SCALAR c[]\fR, \fBLIS_INT op\fR);

.SH DESCRIPTION

Calculate the matrix-matrix product \fIAB\fR.

.SH INPUT

.IP "\fBn\fR"
The size of the matrices

.IP "\fBa\fR"
The array that stores matrix \fIA\fR of size \fIn * n\fR

.IP "\fBb\fR"
The array that stores matrix \fIB\fR of size \fIn * n\fR

.IP "\fBc\fR"
The array that stores matrix \fIC\fR of size \fIn * n\fR

.IP "\fBop\fR"
.RS
.IP "\fBLIS_INS_VALUE\fR"
\fIC\fR = \fIAB\fR
.IP "\fBLIS_SUB_VALUE\fR"
\fIC\fR = \fIC - AB\fR

.SH OUTPUT

.IP "\fBC\fR"
\fIC\fR

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

