.TH lis_matrix_axpyz 3 "30 Dec 2014" "Man Page" "Lis Library Functions"

.SH NAME

lis_matrix_axpyz \- calculate the sum of the matrices

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_matrix_axpyz\fR(\fBLIS_SCALAR alpha\fR, \fBLIS_MATRIX A\fR, \fBLIS_MATRIX B\fR, \fBLIS_MATRIX C\fR);

.SH DESCRIPTION

Calculate the sum of the matrices \fIC = alpha * A + B\fR.

.SH INPUT

.IP "\fBalpha\fR"
The scalar value

.IP "\fBA, B\fR"
The matrices

.SH OUTPUT

.IP "\fBC\fR"
\fIalpha * A + B\fR

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH NOTE

Matrices \fIA\fR, \fIB\fR and \fIC\fR must be in the DNS format.

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

