.TH spmvtest4 1 "26 Mar 2014" "Man Page" "Utility Commands"

.SH NAME

spmvtest4 \- SpMV kernel benchmark for sparse matrix storage formats

.SH SYNOPSIS

\fBspmvtest4\fR \fImatrix_filename_list iter\fR [\fIblock\fR]

.SH DESCRIPTION
This program inputs the matrix data from the files listed in 
\fImatrix_filename_list\fR, and computes the multiplies of matrices 
in available matrix storage formats and a vector (1, ..., 1)^T. The FLOPS 
performance is measured as the average of \fIiter\fR iterations. 
The Matrix Market format is supported for \fImatrix_filename\fR.
If necessary, the block size of the BSR and BSC formats can be specified 
by \fIblock\fR.
See Lis User Guide for more information.

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3),
.BR lsolve (1),
.BR esolve (1),
.BR hpcg_kernel (1),
.BR hpcg_spmvtest (1),
.BR spmvtest1 (1),
.BR spmvtest2 (1),
.BR spmvtest2b (1),
.BR spmvtest3 (1),
.BR spmvtest3b (1),
.BR spmvtest5 (1)
.PP
http://www.ssisc.org/lis/
.br
http://math.nist.gov/MatrixMarket/

