.TH lis_vector_set_all 3 "28 Aug 2014" "Man Page" "Lis Library Functions"

.SH NAME

lis_vector_set_all \- assign the value to the elements of the vector 

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_vector_set_all\fR(\fBLIS_SCALAR value\fR, \fBLIS_VECTOR x\fR);

.SH DESCRIPTION

Assign scalar value \fIvalue\fR to the elements of vector \fIx\fR.

.SH INPUT

.IP "\fBvalue\fR"
The scalar value to be assigned

.IP "\fBx\fR"
The destination vector

.SH OUTPUT

.IP "\fBx\fR"
The vector with the value assigned to the elements

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

