.TH lis_array_qr 3 "1 Nov 2014" "Man Page" "Lis Library Functions"

.SH NAME

lis_array_qr \- calculate the eigenvalues with the QR algorithm

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_array_qr\fR(\fBLIS_INT n\fR, \fBLIS_SCALAR a[]\fR, \fBLIS_SCALAR q[]\fR, \fBLIS_SCALAR r[]\fR, \fBLIS_INT *qriter\fR, \fBLIS_SCALAR *qrerr\fR);

.SH DESCRIPTION

Calculate the eigenvalues of matrix \fIA\fR with the QR algorithm.

.SH INPUT

.IP "\fBn\fR"
The size of the matrices

.IP "\fBa\fR"
The array that stores matrix \fIA\fR of size \fIn * n\fR

.IP "\fBq\fR"
The work array \fIQ\fR of size \fIn * n\fR

.IP "\fBr\fR"
The work array \fIR\fR of size \fIn * n\fR

.SH OUTPUT

.IP "\fBa\fR"
The array that stores the block upper-triangular matrix with eigenvalues in the block diagonal elements after similarity transformation

.IP "\fBqriter\fR"
The number of iterations of the QR algorithm

.IP "\fBqrerr\fR"
The 2-norm of the first subdiagonal element \fIA(2,1)\fR after similarity transformation

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

