.TH lis_matrix_set_bsc 3 "6 Sep 2012" "Man Page" "Lis Library Functions"

.SH NAME

lis_matrix_set_bsc \- associate the arrays in the BSC format with the matrix

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_matrix_set_bsc\fR(\fBLIS_INT bnr\fR, \fBLIS_INT bsc\fR, \fBLIS_INT bnnz\fR, \fBLIS_INT bptr\fR[], \fBLIS_INT bindex\fR[], \fBLIS_SCALAR value\fR[], \fBLIS_MATRIX A\fR);

.SH DESCRIPTION

Associate the arrays in the BSC format with matrix A.

.SH INPUT

.IP "\fBbnr\fR"
The row block size

.IP "\fBbnc\fR"
The column block size

.IP "\fBbnnz\fR"
The number of nonzero blocks

.IP "\fBbptr, bindex, value\fR"
The arrays in the BSC format

.IP "\fBA\fR"
The matrix

.SH OUTPUT

.IP "\fBA\fR"
The matrix associated with the arrays

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH NOTE

After \fBlis_matrix_set_bsc\fR is called, the function \fBlis_matrix_assemble\fR must be called.

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

