.TH lis_vector_get_value 3 "6 Sep 2012" "Man Page" "Lis Library Functions"

.SH NAME

lis_vector_get_value \- get the value of the row of the vector

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_vector_get_value\fR(\fBLIS_INT flag\fR, \fBLIS_INT i\fR, \fBLIS_SCALAR value\fR, \fBLIS_VECTOR v\fR);

.SH DESCRIPTION

Get the scalar value of the \fIi\fR-th row of the vector.

.SH INPUT

.IP "\fBi\fR"
The location where the value is assigned

.IP "\fBv\fR"
The source vector

.SH OUTPUT

.IP "\fBvalue\fR"
The value of the \fIi\fR-th row

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH NOTE

For the multiprocessing environment, the \fIi\fR-th row of the global vector must be specified.

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

