.TH lis_solver_get_iter 3 "28 Aug 2014" "Man Page" "Lis Library Functions"

.SH NAME

lis_solver_get_iter \- get the number of iterations from the solver

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_solver_get_iter\fR(\fBLIS_SOLVER solver\fR, \fBLIS_INT *iter\fR);

.SH DESCRIPTION

Get the number of iterations from the solver.

.SH INPUT

.IP "\fBsolver\fR"
The solver

.SH OUTPUT

.IP "\fBiter\fR"
The number of iterations

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

