.TH lis_vector_scatter 3 "6 Sep 2012" "Man Page" "Lis Library Functions"

.SH NAME

lis_vector_scatter \- scatter the values to the vector

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_vector_scatter\fR(\fBLIS_SCALAR value\fR[], \fBLIS_VECTOR v\fR);

.SH DESCRIPTION

Scatter the values of global array \fIvalue\fR to partial vector \fIv\fR.

.SH INPUT

.IP "\fBvalue\fR"
The array which stores the scalar values to be assigned

.SH OUTPUT

.IP "\fBv\fR"
The destination vector

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

