.TH lis_esolver_get_iters 3 "28 Aug 2014" "Man Page" "Lis Library Functions"

.SH NAME

lis_esolver_get_iters \- get the numbers of iterations for all the eigenpairs from the eigensolver

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_esolver_get_iters\fR(\fBLIS_ESOLVER esolver\fR, \fBLIS_VECTOR v\fR);

.SH DESCRIPTION

Get the numbers of iterations for all the eigenpairs from the eigensolver.

.SH INPUT

.IP "\fBesolver\fR"
The eigensolver

.SH OUTPUT

.IP "\fBv\fR"
The vector which stores the numbers of iterations

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH NOTE
Vector \fIv\fR must be created in advance with the function \fBlis_vector_create\fR.

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

