.TH lis_vector_swap 3 "28 Aug 2014" "Man Page" "Lis Library Functions"

.SH NAME

lis_vector_swap \- swap the values of the vector elements

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_vector_swap\fR(\fBLIS_VECTOR x\fR, \fBLIS_VECTOR y\fR);

.SH DESCRIPTION

Swap the values of the vector elements.

.SH INPUT

.IP "\fBx, y\fR"
The source vectors

.SH OUTPUT

.IP "\fBx, y\fR"
The destination vectors

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

