.TH lis_finalize 3 "6 Sep 2012" "Man Page" "Lis Library Functions"

.SH NAME

lis_finalize \- finalize the execution environment

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_finalize\fR();

.SH DESCRIPTION

Finalize the execution environment.

.SH INPUT

.IP "\fBNone\fR"

.SH OUTPUT

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

