.TH lis_array_ge 3 "3 Dec 2014" "Man Page" "Lis Library Functions"

.SH NAME

lis_array_ge \- calculate the inverse of the matrix with the Gaussian elimination

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_array_ge\fR(\fBLIS_INT n\fR, \fBLIS_SCALAR a[]\fR);

.SH DESCRIPTION

Calculate the inverse \fIA^-1\fRof matrix \fIA\fR with the Gaussian elimination.

.SH INPUT

.IP "\fBn\fR"
The size of the matrix

.IP "\fBa\fR"
The array that stores matrix \fIA\fR of size \fIn * n\fR

.SH OUTPUT

.IP "\fBa\fR"
The inverse of the matrix

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

