.TH lis_vector_copy 3 "28 Aug 2014" "Man Page" "Lis Library Functions"

.SH NAME

lis_vector_copy \- copy the values of the vector elements

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_vector_copy\fR(\fBLIS_VECTOR x\fR, \fBLIS_VECTOR y\fR);

.SH DESCRIPTION

Copy the values of the vector elements.

.SH INPUT

.IP "\fBx\fR"
The source vector

.SH OUTPUT

.IP "\fBy\fR"
The destination vector

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

