.TH lis_matrix_assemble 3 "6 Sep 2012" "Man Page" "Lis Library Functions"

.SH NAME

lis_matrix_assemble \- assemble the matrix into the specified storage format

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_matrix_assemble\fR(\fBLIS_MATRIX A\fR);

.SH DESCRIPTION

Assemble matrix \fIA\fR into the specified storage format.

.SH INPUT

.IP "\fBA\fR"
The matrix

.SH OUTPUT

.IP "\fBA\fR"
The matrix assembled into the specified storage format

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

