.TH lis_esolver_create 3 "6 Sep 2012" "Man Page" "Lis Library Functions"

.SH NAME

lis_esolver_create \- create the eigensolver

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_esolver_create\fR(\fBLIS_ESOLVER *esolver\fR);

.SH DESCRIPTION

Create the eigensolver.

.SH INPUT

.IP "\fBNone\fR"

.SH OUTPUT

.IP "\fBesolver\fR"
The eigensolver

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH NOTE

\fBesolver\fR has the information on the eigensolver, the preconditioner, etc.

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

