.TH lis_vector_nrmi 3 "9 Sep 2014" "Man Page" "Lis Library Functions"

.SH NAME

lis_vector_nrmi \- calculate the infinity norm of the vector

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_vector_nrmi\fR(\fBLIS_VECTOR x\fR, \fBLIS_SCALAR *value\fR);

.SH DESCRIPTION

Calculate the infinity norm of vector \fIx\fR.

.SH INPUT

.IP "\fBx\fR"
The vector

.SH OUTPUT

.IP "\fBvalue\fR"
The infinity norm of the vector

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

