.TH lis_esolver_get_specific_evector 3 "24 Jan 2021" "Man Page" "Lis Library Functions"

.SH NAME

lis_esolver_get_specific_evector \- get the specified eigenvector from the eigensolver

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_esolver_get_specific_evector\fR(\fBLIS_ESOLVER esolver\fR, \fBLIS_INT mode\fR, \fBLIS_VECTOR x\fR);

.SH DESCRIPTION

Get the specified eigenvector from the eigensolver.

.SH INPUT

.IP "\fBesolver\fR"
The eigensolver

.IP "\fBmode\fR"
The mode number of the eigenvector

.SH OUTPUT

.IP "\fBv\fR"
The eigenvector

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

