.TH lis_solver_get_solver 3 "6 Sep 2012" "Man Page" "Lis Library Functions"

.SH NAME

lis_solver_get_solver \- get the solver number from the solver

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_solver_get_solver\fR(\fBLIS_SOLVER solver\fR, \fBLIS_INT *nsol\fR);

.SH DESCRIPTION

Get the solver number from the solver.

.SH INPUT

.IP "\fBsolver\fR"
The solver

.SH OUTPUT

.IP "\fBnsol\fR"
The solver number

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

