.TH lis_initialize 3 "6 Sep 2012" "Man Page" "Lis Library Functions"

.SH NAME

lis_initialize \- initialize the execution environment

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_initialize\fR(\fBLIS_INT* argc\fR, \fBchar** argv\fR[]);

.SH DESCRIPTION

Initialize the execution environment.

.SH INPUT

.IP "\fBargc\fR"
The number of command line arguments

.IP "\fBargv\fR"
The command line argument

.SH OUTPUT

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

