.TH lis_array_scale 3 "3 Dec 2014" "Man Page" "Lis Library Functions"

.SH NAME

lis_array_scale \- multiply the vector by the scalar

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_array_scale\fR(\fBLIS_INT n\fR, \fBLIS_SCALAR alpha\fR, \fBLIS_SCALAR x[]\fR);

.SH DESCRIPTION

Multiply vector \fIx\fR by scalar \fIalpha\fR.

.SH INPUT

.IP "\fBn\fR"
The size of the vector

.IP "\fBalpha\fR"
The scalar value \fIalpha\fR

.IP "\fBx\fR"
The array that stores the vector 

.SH OUTPUT

.IP "\fBx\fR"
\fIalpha * x\fR (vector \fIx\fR is overwritten)

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

