.TH lis_input_matrix 3 "6 Sep 2012" "Man Page" "Lis Library Functions"

.SH NAME

lis_input_matrix \- read the matrix data 

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_input_matrix\fR(\fBLIS_MATRIX A\fR, \fBchar *filename\fR);

.SH DESCRIPTION

Read the matrix data from the external file.

.SH INPUT

.IP "\fBfilename\fR"
The source file

.SH OUTPUT

.IP "\fBA\fR"
The matrix

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH NOTE

The following file formats are supported:
.IP "The Matrix Market format"
.IP "The Harwell-Boeing format"

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

