.TH lis_array_reciprocal 3 "3 Dec 2014" "Man Page" "Lis Library Functions"

.SH NAME

lis_array_reciprocal \- get the reciprocal values of the elements of the vector

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_array_reciprocal\fR(\fBLIS_INT n\fR, \fBLIS_SCALAR x[]\fR);

.SH DESCRIPTION

Get the reciprocal values of the elements of vector \fIx\fR.

.SH INPUT

.IP "\fBn\fR"
The size of the vector

.IP "\fBx\fR"
The array that stores the vector

.SH OUTPUT

.IP "\fBx\fR"
The array that stores the reciprocal values

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

