.TH lis_array_dot 3 "12 Oct 2016" "Man Page" "Lis Library Functions"

.SH NAME

lis_array_dot \- calculate the Hermitian inner product of the vectors

.SH SYNOPSIS

#include "lis.h"

\fBLIS_INT lis_array_dot\fR(\fBLIS_INT n\fR, \fBLIS_SCALAR x[]\fR, \fBLIS_SCALAR y[]\fR, \fBLIS_SCALAR *value\fR);

.SH DESCRIPTION

Calculate the Hermitian inner product \fIy^H x\fR of vectors \fIx\fR and \fIy\fR.

.SH INPUT

.IP "\fBn\fR"
The size of the vectors

.IP "\fBx, y\fR"
The arrays that store the vectors

.SH OUTPUT

.IP "\fBvalue\fR"
The Hermitian inner product

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3)
.PP
http://www.ssisc.org/lis/

