/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to a macro mangling the given C identifier (in lower and upper
   case), which must not contain underscores, for linking with Fortran. */
#define F77_FUNC(name,NAME) NAME

/* As F77_FUNC, but for C identifiers containing underscores. */
#define F77_FUNC_(name,NAME) NAME

/* Define to 1 to have x87 FPU. */
/* #undef HAS_X87_FPU 1 */

/* Define to 1 to build Quad precision. */
/* #undef USE_QUAD_PRECISION 1 */

/* Define to 1 to build Quad precision. */
/* #undef USE_FMA2_SSE2 1 */

/* Define to 1 to build Quad precision. */
/* #undef USE_SSE2 1 */
/* #undef USE_FAST_QUAD_ADD 1 */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "devel@ssisc.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "lis"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "lis 1.5.40"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "lis"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.5.40"

