.TH gesolve 1 "4 Nov 2017" "Man Page" "Utility Commands"

.SH NAME

gesolve \- eigensolver for generalized eigenvalue problems

.SH SYNOPSIS

\fBgesolve\fR \fImatrix_a_filename matrix_b_filename evalues_filename evectors_filename residuals_filename iters_filename\fR [\fIoptions\fR]

.SH DESCRIPTION

This program inputs the matrix data from \fImatrix_a_filename\fR \fImatrix_b_filename\fR, and solves the 
generalized eigenvalue problem A*x = l*B*x with the solver specified by \fIoptions\fR.
It outputs the specified number of eigenvalues, the number of which is 
given by option \fI-ss\fR, to \fIevalues_filename\fR
and the associated eigenvectors, residual norms, and numbers of iterations to 
\fIevectors_filename\fR, \fIresiduals_filename\fR, and \fIiters_filename\fR
respectively
in the extended Matrix Market format (see Appendix of Lis User Guide). Both the
Matrix Market format and the Harwell-Boeing format are supported for the matrix filenames.

.SH OPTIONS

The following options are supported:
.IP "-e \fIeigensolver\fR"
The following options are supported for \fIeigensolver\fR:
.RS 
.IP "-e {\fIgpi\fR|9}"
Generalized Power
.IP "-e {\fIgii\fR|10}"
Generalized Inverse
.IP "-e {\fIgrqi\fR|11}"
Generalized Rayleigh Quotient
.IP "-e {\fIgcg\fR|12}"
Generalized CR
.IP "-e {\fIgcr\fR|13}"
Generalized CR
.IP "-e {\fIgsi\fR|14}"
Generalized Subspace
.RS
.IP "-ss [1]"
The size of the subspace
.RE
.IP "-e {\fIgli\fR|15}"
Generalized Lanczos
.RS
.IP "-ss [1]"
The size of the subspace
.RE
.IP "-e {\fIgai\fR|16}"
Generalized Arnoldi
.RS
.IP "-ss [1]"
The size of the subspace
.RE
.RE
.IP "-i \fIlinear solver\fR"
The following options are supported for inner \fIlinear solver\fR:
.RS 
.IP "-i {\fIcg\fR|1}"
CG
.IP "-i {\fIbicg\fR|2}"
BiCG
.IP "-i {\fIcgs\fR|3}"
CGS
.IP "-i {\fIbicgstab\fR|4}"
BiCGSTAB
.IP "-i {\fIbicgstabl\fR|5}"
BiCGSTAB(l)
.RS
.IP "-ell [2]"
The degree \fIl\fR
.RE
.IP "-i {\fIgpbicg\fR|6}"
GPBiCG
.IP "-i {\fItfqmr\fR|7}"
TFQMR
.IP "-i {\fIorthomin\fR|8}"
Orthomin(m)
.RS
.IP "-restart [40]"
The restart value \fIm\fR
.RE
.IP "-i {\fIgmres\fR|9}"
GMRES(m)
.RS
.IP "-restart [40]"
The restart value \fIm\fR
.RE
.IP "-i {\fIjacobi\fR|10}"
Jacobi
.IP "-i {\fIgs\fR|11}"
Gauss-Seidel
.IP "-i {\fIsor\fR|12}"
SOR
.RS
.IP "-omega [1.9]"
The relaxation coefficient \fIomega\fR (0<\fIomega\fR<2)
.RE
.IP "-i {\fIbicgsafe\fR|13}"
BiCGSafe
.IP "-i {\fIcr\fR|14}"
CR
.IP "-i {\fIbicr\fR|15}"
BiCR
.IP "-i {\fIcrs\fR|16}"
CRS
.IP "-i {\fIbicrstab\fR|17}"
BiCRSTAB
.IP "-i {\fIgpbicr\fR|18}"
GPBiCR
.IP "-i {\fIbicrsafe\fR|19}"
BiCRSafe
.IP "-i {\fIfgmres\fR|20}"
FGMRES(m)
.RS
.IP "-restart [40]"
The restart value \fIm\fR
.RE
.IP "-i {\fIidrs\fR|21}"
IDR(s)
.RS
.IP "-irestart [2]"
The restart value \fIs\fR
.RE
.IP "-i {\fIidr1\fR|22}"
IDR(1)
.IP "-i {\fIminres\fR|23}"
MINRES
.IP "-i {\fIcocg\fR|24}"
COCG
.IP "-i {\fIcocr\fR|25}"
COCR
.RE

.IP "-p \fIpreconditioner\fR"
The following options are supported for \fIpreconditioner\fR:
.RS 
.IP "-p {\fInone\fR|0}"
None
.IP "-p {\fIjacobi\fR|1}"
Jacobi
.IP "-p {\fIilu\fR|2}"
ILU(k)
.RS 
.IP "-ilu_fill [0]"
The fill level \fIk\fR
.RE
.IP "-p {\fIssor\fR|3}"
SSOR
.RS 
.IP "-ssor_omega [1.0]"
The relaxation coefficient \fIomega\fR (0<\fIomega\fR<2)
.RE
.IP "-p {\fIhybrid\fR|4}"
Hybrid
.RS 
.IP "-hybrid_i [\fIsor\fR]"
The linear solver
.RE
.RS 
.IP "-hybrid_maxiter [25]"
The maximum number of the iterations
.RE
.RS 
.IP "-hybrid_tol [1.0e-3]"
The convergence criterion
.RE
.RS 
.IP "-hybrid_omega [1.5]"
The relaxation coefficient \fIomega\fR of the SOR (0<\fIomega\fR<2)
.RE
.RS 
.IP "-hybrid_ell [2]"
The degree \fIl\fR of the BiCGSTAB(l)
.RE
.RS 
.IP "-hybrid_restart [40]"
The restart values of the GMRES and Orthomin
.RE
.IP "-p {\fIis\fR|5}"
I+S
.RS 
.IP "-is_alpha [1.0]"
The parameter \fIalpha\fR of \fII+alpha*S(m)\fR
.RE
.RS 
.IP "-is_m [3]"
The parameter \fIm\fR of \fII+alpha*S(m)\fR
.RE
.IP "-p {\fIsainv\fR|6}"
SAINV
.RS 
.IP "-sainv_drop [0.05]"
The drop criterion
.RE
.IP "-p {\fIsaamg\fR|7}"
SA-AMG
.RS 
.IP "-saamg_unsym [\fIfalse\fR]"
Select the unsymmetric version (The matrix structure must be symmetric)
.RE
.RS 
.IP "-saamg_theta [0.05|0.12]"
The drop criterion
.RE
.IP "-p {\fIiluc\fR|8}"
Crout ILU
.RS 
.IP "-iluc_drop [0.05]"
The drop criterion
.RE
.RS 
.IP "-iluc_rate [5.0]"
The ration of maximum fill-in
.RE
.IP "-p {\fIilut\fR|9}"
ILUT
.RS 
.IP "-ilut_drop [0.05]"
The drop criterion
.RE
.RS 
.IP "-ilut_rate [5.0]"
The ration of maximum fill-in
.RE
.IP "-adds \fItrue\fR"
Additive Schwarz
.RS 
.IP "-adds_iter [1]"
The number of the iteration
.RE
.RE

Other Options for eigensolver:
.IP "-emaxiter [1000]"
The maximum number of the iterations
.IP "-etol [1.0e-12]"
The convergence criterion
.IP "-eprint [0]"
The output of the residual history
.RS 
.IP "-eprint {\fInone\fR|0}"
None
.RE
.RS 
.IP "-eprint {\fImem\fR|1}"
Save the residual history
.RE
.RS 
.IP "-eprint {\fIout\fR|2}"
Output it to the standard output
.RE
.RS 
.IP "-eprint {\fIall\fR|3}"
Save the residual history and output it to the standard output
.RE
.IP "-ige [gii]"
The inner eigensolver used in generalized Subspace, generalized Lanczos, and generalized Arnoldi
.IP "-shift [0.0]"
The amount of the shift
.IP "-initx_ones [\fItrue\fR]"
The behavior of the initial vector \fIx_0\fR
.RS 
.IP "-initx_ones {\fIfalse\fR|0}"
Given values
.RE
.RS 
.IP "-initx_ones {\fItrue\fR|1}"
All values are set to 1
.RE
.IP "-omp_num_threads [\fIt\fR]"
The number of the threads (\fIt\fR represents the maximum number of the threads)
.IP "-estorage [0]"
The matrix storage format
.IP "-estorage_block [2]"
The block size of the BSR and BSC formats
.IP "-ef [0]"
The precision of the eigensolver
.RS 
.IP "-ef {\fIdouble\fR|0}"
Double precision
.RE
.RS
.IP "-ef {\fIquad\fR|1}"
Double-double (quadruple) precision
.RE

Other options for inner linear solver:
.IP "-maxiter [1000]"
The maximum number of the iterations
.IP "-tol [1.0e-12]"
The convergence criterion
.IP "-print [0]"
The output of the residual history
.RS 
.IP "-print {\fInone\fR|0}"
None
.RE
.RS 
.IP "-print {\fImem\fR|1}"
Save the residual history
.RE
.RS 
.IP "-print {\fIout\fR|2}"
Output it to the standard output
.RE
.RS 
.IP "-print {\fIall\fR|3}"
Save the residual history and output it to the standard output
.RE
.IP "-scale [0]"
The scaling
.RS
.IP "-scale {\fInone\fR|0}"
No scaling
.RE
.RS
.IP "-scale {\fIjacobi\fR|1}"
The Jacobi scaling
.RE
.RS
.IP "-scale {\fIsymm_diag\fR|2}"
The diagonal scaling
.RE
.IP "-initx_zeros [\fItrue\fR]"
The behavior of the initial vector \fIx_0\fR
.RS 
.IP "-initx_zero {\fIfalse\fR|0}"
Given values
.RE
.RS 
.IP "-initx_zero {\fItrue\fR|1}"
All values are set to 0
.RE
.IP "-omp_num_threads [\fIt\fR]"
The number of the threads (\fIt\fR represents the maximum number of the threads)
.IP "-storage [0]"
The matrix storage format
.IP "-storage_block [2]"
The block size of the BSR and BSC formats
.IP "-f [0]"
The precision of the linear solver
.RS 
.IP "-f {\fIdouble\fR|0}"
Double precision
.RE
.RS
.IP "-f {\fIquad\fR|1}"
Double-double (quadruple) precision
.RE
.RE

See Lis User Guide for full description.

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3),
.BR lsolve (1),
.BR hpcg_kernel (1),
.BR hpcg_spmvtest (1),
.BR spmvtest1 (1),
.BR spmvtest2 (1),
.BR spmvtest2b (1),
.BR spmvtest3 (1),
.BR spmvtest3b (1),
.BR spmvtest4 (1),
.BR spmvtest5 (1)
.PP
http://www.ssisc.org/lis/
.br
http://math.nist.gov/MatrixMarket/

