.TH spmvtest2b 1 "26 Mar 2014" "Man Page" "Utility Commands"

.SH NAME

spmvtest2b \- SpMV kernel benchmark of two dimensional Laplacian

.SH SYNOPSIS

\fBspmvtest1\fR \fIm n iter\fR [\fImatrix_type\fR]

.SH DESCRIPTION

This program computes the matrix-vector multiply of a discretized 
two dimensional Laplacian of size mn using the nine point 
central difference scheme, and a vector (1, ..., 1)^T. The FLOPS 
performance is measured as the average of \fIiter\fR iterations. 
If necessary, one of the following values can be specified by \fImatrix_type\fR:
.IP "0"
Measure the performance for the available matrix storage formats
.IP "1-11"
The number of the matrix storage format
.PP
The values \fIm\fR and \fIn\fR represent the numbers of the grid points in each dimension.
See Lis User Guide for more information.

.SH EXIT STATUS

The following exit values are returned:
.IP "0"
The process is normally terminated
.IP "unspecified"
An error occurred

.SH SEE ALSO

.BR lis (3),
.BR lsolve (1),
.BR esolve (1),
.BR hpcg_kernel (1),
.BR hpcg_spmvtest (1),
.BR spmvtest1 (1),
.BR spmvtest2 (1),
.BR spmvtest3 (1),
.BR spmvtest3b (1),
.BR spmvtest4 (1),
.BR spmvtest5 (1)
.PP
http://www.ssisc.org/lis/

